# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy v 3.0

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: JavaPetstore  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  JAVA_VERSION: '1.8'                # set this to the java version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}   

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BookingDemo

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./BookingDemo
       # run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: ./BookingDemo

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: 'target/BookingDemo-0.0.1-SNAPSHOT.war'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'afkl-demo-app-java'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8257B7104FCA431F9985F428B214E831 }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war'
          #package: 'target/*.war'
